on:
  pull_request:
    branches:
      - master
    types: [closed, converted_to_draft]
  pull_request_review:
    types: [submitted]


jobs:
  mark-waiting-on-author:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: S-waiting-on-author
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: S-waiting-on-review
